spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/teste?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    platform: development
